NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.kiesnet.dev-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.kiesnet.dev-cert.pem
    OrganizationalUnitIdentifier: peer
